name: ${project.name}
version: ${project.version}
author: ${project.author}
description: ${project.description}

main: ${project.main}

depend: ${project.depend}
softdepend: ${project.softdepend}

permissions:
  moneyitems.notify.updates:
    description: notifies players with this permission of plugin updates
    default: op
