name: ${project.name}
version: ${project.version}
description: ${project.description}
author: SonarBeserk

main: me.sonarbeserk.moneyitems.MoneyItems

softdepend: [Vault]

permissions:
  moneyitems.notify.updates:
    description: notifies players with this permission of plugin updates
    default: op